name: web deployment

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: deploy tomcat
      run: curl -v -u manager:admin -T /home/runner/work/mvn-git-action-tomcat/mvn-git-action-tomcat/target/spring3-mvc-maven-xml-hello-world-3.0-SNAPSHOT.war 'http://ec2-52-66-214-26.ap-south-1.compute.amazonaws.com:8080/manager/text/deploy?path=%2ftomcat'
  

    


    
